spring:
  application:
    name: bank-rest

  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: bankuser
    password: bankpass
    driver-class-name: org.postgresql.Driver
    hikari:
      initializationFailTimeout: -1
      connectionTimeout: 5000

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  liquibase:
    change-log: classpath:db/migration/changelog-master.yml
    enabled: true

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:MySecretKeyForJWTTokenGenerationThatShouldBeAtLeast256BitsLong}
  accessExpiration: 900000   # 15 минут
  refreshExpiration: 1209600000 # 14 дней

card:
  enc:
    secret: ${CARD_ENC_SECRET:MySecretKeyForEncryptionOfCardNumbers256}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

logging:
  level:
    com.example.bankcards: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
